---
refresh_interval: 2 # seconds
max_price: 800 # dollars/euros/etc
urls:
 - https://www.amazon.de/-/nl/dp/B08MKSYYZ4/
 - https://www.amazon.de/-/nl/dp/B08HM4V2DH/
 - https://www.amazon.de/-/nl/dp/B08LTKLG5K/
 - https://www.amazon.de/-/nl/dp/B08HM4M621/
 - https://www.amazon.de/-/nl/dp/B08T7BRWQ9/
 - https://www.amazon.de/-/nl/dp/B08T79PFR3/
 - https://www.amazon.de/-/nl/dp/B08T77ZP44/
 - https://www.amazon.de/-/nl/dp/B08T7CDS7H/
 - 

...
