---
urls:
  - https://www.amazon.nl/Samsung-7-000-Stagiairs-Solid-MZ-V8P1T0BW/dp/B08GS7748F/
  - https://www.amazon.nl/Samsung-Intern-Solid-State-Drive/dp/B07CGGRYVT/
  - https://www.amazon.nl/Samsung-7-000-Interne-Solid-MZ-V8P2T0BW/dp/B08QJHLC8J/
  - https://www.amazon.de/-/nl/dp/B08GS7748F/
  - https://www.amazon.de/-/nl/dp/B07CGGRYVT/
  - https://www.amazon.de/-/nl/dp/B08QJHLC8J/
  - https://www.amazon.de/-/nl/dp/B07MBQPQ62/
  - https://www.amazon.de/-/nl/dp/B07ND9KHKY/
  - https://www.amazon.nl/Samsung-Intern-Solid-State-Drive/dp/B07MLJD32L/
  - https://www.amazon.de/-/nl/dp/B07MLJD32L/
  - https://www.amazon.de/-/nl/dp/B07MFZXR1B/
  - https://www.bol.com/nl/p/samsung-970-evo-plus-m-2-ssd-1tb/9200000104794052
  - https://www.bol.com/nl/p/samsung-970-evo-plus-m-2-2000-gb-pci-express-3-0-v-nand-mlc-nvme/9200000104794050/
...
