---
refresh_interval: 1 # seconds
max_price: 105 # dollars/euros/etc
urls:
  - https://www.amazon.nl/dp/B07CGJNLBB/
  - https://www.amazon.nl/dp/B07BN217QG/
  - https://www.amazon.de/-/nl/dp/B07CGJNLBB/
  - https://www.amazon.de/-/nl/dp/B07BN217QG/
  - https://www.amazon.nl/dp/B07MBQPQ62/
  - https://www.amazon.de/-/nl/dp/B07MBQPQ62/
  - https://www.amazon.de/-/nl/dp/B07MFZY2F2/
  - https://www.amazon.de/-/nl/dp/B07ND9KHKY/
  - https://www.bol.com/nl/p/samsung-970-evo-m-2-1tb/9200000093062528/
...