---
refresh_interval: 2 # seconds
max_price: 650 # dollars/euros/etc
urls:
  - https://www.amazon.de/-/nl/dp/B08KHL21CV/
  - https://www.amazon.de/-/nl/dp/B08QZP2RRS/
  - https://www.amazon.de/-/nl/dp/B08LNQTSCT/
  - https://www.amazon.de/-/nl/dp/B08LLG9KQT/
  - https://www.amazon.de/-/nl/dp/B08MWS59K8/
  - https://www.amazon.de/-/nl/dp/B08LBVNKT1/
  - https://www.amazon.de/-/nl/dp/B08NZ5FN7Q/
  - https://www.amazon.de/-/nl/dp/B08KHFZN9P/
  - https://www.amazon.de/-/nl/dp/B08HBF5L3K/
  - https://www.amazon.de/-/nl/dp/B08HBJB7YD/
  - https://www.amazon.de/-/nl/dp/B08P7ZKQPP/
  - https://www.amazon.de/-/nl/dp/B08L8LG4M3/
  - https://www.amazon.de/-/nl/dp/B08LDS72P2/
  - https://www.amazon.de/-/nl/dp/B08LDT6HQ5/
  - https://www.amazon.de/-/nl/dp/B08NT9WQBG/
  - https://www.amazon.de/-/nl/dp/B08L6PCZTR/
  - https://www.amazon.de/-/nl/dp/B08R427DMQ/
  - https://www.amazon.de/-/nl/dp/B08HT7PR9Y/
  - https://www.amazon.de/-/nl/dp/B08MYCN952/
  - https://www.amazon.de/-/nl/dp/B08L6PCZTR/
  - https://www.amazon.nl/EVGA-GeForce-Gaming-08G-P5-3751-KR-Cooling/dp/B08L3QCZKZ/
  - https://www.amazon.nl/GIGABYTE-grafische-GV-N3070GAMING-OC-8GD-videokaart/dp/B08KY266MG/
  - https://www.amazon.nl/PNY-GeForce-RTXTM-UPRISING-grafische/dp/B08HBF5L3K/
  - https://www.amazon.nl/PNY-GeForce-Gaming-EPIC-X-grafische/dp/B08HBJB7YD/
  - https://www.amazon.nl/ZOTAC-GeForce-grafische-kaart-ZT-A30700E-10P/dp/B08HRBR7K9/
  - https://www.amazon.nl/Gigabyte-GeForce-EAGLE-grafische-kaart/dp/B08KHL2J5X/
  - https://www.amazon.nl/GUOJIAYI-iGame-videokaart-gamecomputer-desktop/dp/B08NGFHYPQ/
  - https://www.amazon.nl/KFA2-GeForce-3070-1-Click-GDDR6/dp/B08T7KNBC6/
  - https://www.amazon.nl/ASUS-grafische-geheugen-DisplayPort-DUAL-RTX3070-8G/dp/B08HSJ1622/
  - https://www.amazon.nl/Palit-GamingPro-Ray-Tracing-grafische-DisplayPort/dp/B08LDS72P2/
  - https://www.amazon.nl/GeForce-RTX-3070-VENTUS-2X/dp/B08LNQTSCT/
  - https://www.amazon.nl/ZOTAC-grafische-Geavanceerde-LED-logoverlichting-ZT-A30700H-10P/dp/B08LF1CWT2/
  - https://www.amazon.nl/EVGA-08G-P5-3755-KR-GeForce-Koeling-Backplate/dp/B08L8L71SM/
  - https://www.amazon.nl/GeForce-grafische-DisplayPort-axiaal-tech-ventilator/dp/B08BL4K6LN/
  - https://www.amazon.nl/GIGABYTE-grafische-GV-N3070AORUS-M-8GD-videokaart/dp/B08M14Y3C7/
  - https://www.amazon.nl/Gigabyte-grafische-WINDFORCE-GV-N3070EAGLE-8GD-videokaart/dp/B08KXZV626/
  - https://www.amazon.nl/EVGA-08G-P5-3751-KR-GeForce-Gaming-Koeling/dp/B08LW46GH2/
  - https://www.amazon.nl/GeForce-RTX-3070-Architectuur-VENTUS/dp/B08KWPDXJZ/
  - https://www.amazon.nl/ASUS-grafische-DisplayPort-Axial-tech-Beschermende/dp/B08L8HPKR6/
  - https://www.amazon.nl/Gainward-GeForce-Phoenix-Gaming-graphics/dp/B08LQ4XF6Z/
  - https://www.amazon.nl/ASUS-grafische-DisplayPort-militaire-certificering/dp/B08L8KC1J7/
  - https://www.amazon.nl/Gigabyte-GeForce-EAGLE-grafische-kaart/dp/B08MDCF8Z8/
  - https://www.amazon.nl/Palit-GamingPro-Ray-Tracing-grafische-DisplayPort/dp/B08LDT6HQ5/
  - https://www.amazon.nl/ASUS-grafische-DisplayPort-kleurenschema-Axial-tech/dp/B08R15HVJ3/
  - https://www.amazon.nl/ASUS-grafische-DisplayPort-Axial-tech-Beschermende/dp/B08L8LG4M3/
  - https://www.amazon.nl/MSI-RTX-3070-Gaming-Trio/dp/B08LNPPCWJ/
  - https://www.amazon.nl/Gainward-VGA-GeForce®-3070-Phoenix/dp/B08LQBLGGZ/
  - https://www.amazon.nl/Palit-GeForce-GameRock-grafische-DisplayPort/dp/B08QZQJZBW/
  - https://www.amazon.nl/Palit-GeForce-GameRock-grafische-DisplayPort/dp/B08NT9WQBG/
  - https://www.amazon.nl/KFA2-GeForce-Serious-PCI-Express-grafische/dp/B08LNW8RR4/
  - https://www.amazon.nl/EVGA-GeForce-Ultra-Gaming-graphics/dp/B08MKWZZ2G/
  - https://www.amazon.nl/ASUS-DisplayPort-Axial-tech-technologie-condensators/dp/B08MT6B58K/
  - https://www.amazon.nl/EVGA-GeForce-08G-P5-3753-KR-Cooling-backplaat/dp/B08L3QZP7W/
  - https://www.amazon.nl/EVGA-GeForce-08G-P5-3755-KR-Cooling-backplaat/dp/B08L3Q41SM/
...