---
urls:
  - https://www.amazon.nl/Samsung-7-000-Stagiairs-Solid-MZ-V8P1T0BW/dp/B08GS7748F/
  - https://www.amazon.nl/Samsung-Intern-Solid-State-Drive/dp/B07CGGRYVT/
  - https://www.amazon.nl/Samsung-7-000-Interne-Solid-MZ-V8P2T0BW/dp/B08QJHLC8J/
  - https://www.amazon.de/-/nl/dp/B08GS7748F/
  - https://www.amazon.de/-/nl/dp/B07CGGRYVT/
  - https://www.amazon.de/-/nl/dp/B08QJHLC8J/
...
